<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/04/13 02:25:27

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=takutomo',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
